#!/bin/bash
# Produce pushback.pm from the literate markdown source

set -euo pipefail
cd "$(dirname "$0")"

rm -f pushback.pm
./unlit --perl README.md > pushback.pm

# The result is read-only because editing it is the wrong idea; you want to edit
# the markdown source instead.
chmod 444 pushback.pm
