#!/usr/bin/env perl
use strict;
use warnings;
no warnings 'void';

BEGIN { push @INC, $0 =~ s#[^/]*$#..#r }
use pushback;

my $io   = pushback::io->new;
my $copy = $io->read(\*STDIN) >> $io->write(\*STDOUT);
$io << $copy;

while ($copy->running)
{
  my ($r, $w, $e, $timeout) = $io->select_args;
  select $$r, $$w, $$e, $timeout;
  $io->step;
}
