#!/usr/bin/env perl
use strict;
use warnings;
no warnings 'void';

BEGIN { push @INC, $0 =~ s#[^/]*$#..#r }
use pushback;

pipe my $r, my $w or die $!;

my $io    = pushback::io->new;
my $copy1 = $io->read(\*STDIN) >> $io->write($w);
my $copy2 = $io->read($r) >> $io->write(\*STDOUT);
$io << $copy1
    << $copy2;

while ($copy1->running && $copy2->running)
{
  my ($r, $w, $e, $timeout) = $io->select_args;
  select $$r, $$w, $$e, $timeout;
  $io->step;
}
