#!/usr/bin/env perl
use strict;
use warnings;
no warnings 'void';

BEGIN { push @INC, $0 =~ s#[^/]*$#..#r }
use pushback;

pipe my $r, my $w or die $!;

my $copy1 = io->read(\*STDIN) >> io->write($w);
my $copy2 = io->read($r) >> io->write(\*STDOUT);
io << $copy1
   << $copy2;

io->select_loop;
