#!/usr/bin/env perl
use strict;
use warnings;
no warnings 'void';

BEGIN { push @INC, $0 =~ s#[^/]*$#..#r }
use pushback;

my $io = pushback::io->new;
$io << ($io->tcp_server(8080) >> $io->each(sub {
  my ($reader, $writer, $paddr) = @_;
  $io << ($reader >> $writer) if $paddr;
}));

$io->select_loop;
