#!/usr/bin/env perl
use strict;
use warnings;
use Benchmark qw/timethese/;

my %h = map +($_ => 0), 0..8191;
my $v = "\0" x 1024;

my @is = map int(rand 8192), 1..10;
my @rs = map \vec($v, $_, 1), 0..8191;

timethese 1_000_000, {
  hash    => sub { my $i = 0; $i += $h{$_} for @is; $i },
  hasharr => sub { my $i = 0; $i += $_ for @h{@is}; $i },
  vec     => sub { my $i = 0; $i += vec $v, $_, 1 for @is; $i },
  vecref  => sub { my $i = 0; $i += $$_ for @rs[@is]; $i },
  vecind  => sub { my $i = 0; $i += $rs[$_] for @is; $i },
};
