#!/usr/bin/env perl
use strict;
use warnings;

my $r = \[1, 2, 3];
my $v1 = ${${$r}}[0];
my $v2 = $${$r}[0];
my $v3 = $$$r[0];

my @v1 = @{${$r}}[0, 2];
my @v2 = @${$r}[0, 2];
my @v3 = @$$r[0, 2];

print "$v1, $v2, $v3, @v1, @v2, @v3\n";
