#!/usr/bin/env perl
use strict;
use warnings;
use Benchmark qw/timethese/;

my $n  = 0;
my $rn = \$n;

timethese 1000000, {
  direct => sub { ++$n   for 1..100 },
  ref    => sub { ++$$rn for 1..100 },
};
