#!/usr/bin/env perl
use strict;
use warnings;
use Scalar::Util qw/refaddr/;

package foo;
sub DESTROY
{
  print "destroying\n";
  push @bar::oops, shift;
}

{
  my $x = bless { x => 10 }, 'foo';
  print "end of block\n";
}

print "outside block; oops[0]{x} = $bar::oops[0]{x}\n";

@bar::oops = ();
