#!/usr/bin/env perl
use strict;
use warnings;

package foo;
sub DESTROY { print "foo destroy\n" }

package bar;
push our @ISA, 'foo';
sub DESTROY { print "bar destroy\n" }

package bif;
push our @ISA, 'foo';
sub DESTROY { shift->SUPER::DESTROY; print "bif destroy\n" }

{
  bless {}, 'bif';
}
