#!/usr/bin/env perl
use strict;
use warnings;
use Benchmark qw/timethese/;

my $x = 0;
my $obscenely_long_variable_name_perl_please_dont_disappoint_me_here = 0;

timethese 40000000, {
  short => sub { $x += 1 },
  long  => sub {
    $obscenely_long_variable_name_perl_please_dont_disappoint_me_here += 1 },
};
